apiVersion: v1
kind: Secret
metadata:
  name: worker-user-data
  namespace: openshift-machine-api
type: Opaque
data:
  disableTemplating: WorkerUserDataDisableTemplating
  userData: WorkerUserDataSecret
