apiVersion: v1
data:
  install-config: |
    apiVersion: v1beta3
    baseDomain: devcluster.openshift.com
    metadata:
      creationTimestamp: null
      name: kni-edge
    compute:
      - name: worker
        platform: {}
        replicas: 3
    controlPlane:
      name: master
      platform: {}
      replicas: 3
    networking:
      clusterNetworks:
        - cidr: 10.128.0.0/14
          hostSubnetLength: 9
      machineCIDR: 10.0.0.0/16
      serviceCIDR: 172.30.0.0/16
      type: OpenShiftSDN
    platform:
      aws:
        region: us-west-1
    pullSecret: '{{.pullSecret }}'
    sshKey: |
        {{ .SSHKey }}
kind: ConfigMap
metadata:
    name: cluster-config-v1
    namespace: kube-system
