apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - manifests/04-openshift-machine-config-operator.yaml
    - manifests/cluster-config.yaml
    - manifests/cluster-dns-02-config.yml
    - manifests/cluster-infrastructure-02-config.yml
    - manifests/cluster-ingress-02-config.yml
    - manifests/cluster-network-01-crd.yml
    - manifests/cluster-network-02-config.yml
    - manifests/cvo-overrides.yaml
    - manifests/etcd-service.yaml
    - manifests/host-etcd-service-endpoints.yaml
    - manifests/host-etcd-service.yaml
    - manifests/kube-cloud-config.yaml
    - manifests/kube-system-configmap-etcd-serving-ca.yaml

